// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzrxsxsllytmtahvoqur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cnhzeHNsbHl0bXRhaHZvcXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDE2NjcsImV4cCI6MjA2MTQ3NzY2N30.FSUX2AtpNl0XlRPEmLPw5n4eYMoL7TspOQAfPhx9jn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);